add composite img and ktx image loader
shenfy/imgpp pull request #25
Opened 2020-08-14 08:36 UTC by ZihaoTu

2020-08-14 09:05 UTC, chubei-oppen commented on src/CMakeLists.txt
> +  include/imgpp/textureformat.hpp
bump version

2020-08-14 09:05 UTC, chubei-oppen commented on src/include/imgpp/compositeimg.hpp
> +    customized_info_.insert_or_assign(key, value);
std::move(key), std::move(value)

2020-08-14 09:05 UTC, chubei-oppen commented on src/include/imgpp/compositeimg.hpp
> +  void SetInfo(const std::string &key, const std::string &value) {
just pass by value?

2020-08-14 09:05 UTC, chubei-oppen commented on src/src/ktximage.cpp
> +  if (!kv_map.empty()) {
unnecessary if

2020-08-14 09:05 UTC, chubei-oppen commented on src/src/ktximage.cpp
> +  uint32_t total_size = ComputeKTXStorageSize(composite_img);
why allocate the whole file?

2020-08-14 09:05 UTC, chubei-oppen commented on src/src/ktximage.cpp
> +  std::ofstream out(fn, std::ios::binary);
try open file before doing all the heavy work

2020-08-14 09:05 UTC, chubei-oppen commented on src/src/ktximage.cpp
> +  return true;
return out.good()

2020-08-14 09:05 UTC, chubei-oppen commented on src/src/ktxloadertest.cpp
> +int main(int argc, char* argv[]) {
ctest test can't be implemented like this

2020-08-17 08:28 UTC, shenfy requested changes

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/gl.hpp
> +inline InternalFormat TranslateFromES20(InternalFormat internal) {
move functions to cpp file in an anonymous namespace

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +#include <string>
remove

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +  void SetTextureDesc(TextureDesc desc) {
use reference or move to avoid copying twice.

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +  const TextureDesc &GetTextureDesc() const {
change name to TextureDesc()

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +      img_rois_[0] = roi;
move or emplace_back

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +  void SetSize(uint32_t levels, uint32_t layers, uint32_t faces,
change method name, be explicit about this being a BC image

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +  CompositeImg(TextureDesc desc, uint32_t levels, uint32_t layers, uint32_t faces)
invalid constructor! ROIs not allocated!

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +      bcimg_rois_[level * layers_ * faces_ + layer * faces_ + face] = bcimg_roi;
use move or emplace_back

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +      img_rois_[level * layers_ * faces_ + layer * faces_ + face] = roi;
use move or emplace_back

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/compositeimg.hpp
> +  const ImgROI &ROI(uint32_t level, uint32_t layer, uint32_t face) const {
why not provide access to non-const ROI?

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/gl.hpp
> +enum InternalFormat: uint16_t {
move all GL macro definitions into cpp anonymous namespace.

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/gl.hpp
> +TextureFormat Find(InternalFormat internal, ExternalFormat external,
change name to TranslateFromGL

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/gl.hpp
> +FormatDesc Translate(TextureFormat format, Profile profile);
change name to Translate2GL

2020-08-17 08:28 UTC, shenfy commented on src/include/imgpp/gl.hpp
> +struct FormatDesc {
change type and names: e.g. uint16_t internal_format

2020-08-17 08:43 UTC, chubei-oppen commented on src/src/ktximage.cpp
> +  int64_t kv_left = ktx_header.bytes_of_key_value_data;
custom_data.clear();

2020-08-18 03:04 UTC, merged